# Generated by Django 5.1.2 on 2024-10-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
