# Generated by Django 5.1.2 on 2024-10-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_employee_date_joined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
